// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(WhereAreWeDbContext))]
    [Migration("20261007105006_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Model.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Stockholm"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Göteborg"
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Malmö"
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Uppsala"
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Västerås"
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Örebro"
                        },
                        new
                        {
                            CityId = 7,
                            Name = "Linköping"
                        },
                        new
                        {
                            CityId = 8,
                            Name = "Helsingborg"
                        },
                        new
                        {
                            CityId = 9,
                            Name = "Umeå"
                        },
                        new
                        {
                            CityId = 10,
                            Name = "Lund"
                        });
                });

            modelBuilder.Entity("Backend.Model.Clue", b =>
                {
                    b.Property<int>("ClueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClueId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClueName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Point")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ClueId");

                    b.HasIndex("CityId");

                    b.ToTable("Clues");

                    b.HasData(
                        new
                        {
                            ClueId = 1,
                            CityId = 1,
                            ClueName = "Vi reser till en stad mellan en stor insjö och Östersjön.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 2,
                            CityId = 1,
                            ClueName = "Här finns en kunglig bostad och byggnaden där Nobelbanketten hålls.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 3,
                            CityId = 1,
                            ClueName = "Ett välbevarat krigsskepp från 1600-talet finns på ett museum här.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 4,
                            CityId = 1,
                            ClueName = "Gamla stan och Djurgården är välkända delar av staden.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 5,
                            CityId = 1,
                            ClueName = "Vi söker Sveriges huvudstad.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 6,
                            CityId = 2,
                            ClueName = "Vi reser till en stad vid västkusten med en lång sjöfartshistoria.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 7,
                            CityId = 2,
                            ClueName = "Staden grundades av Gustav II Adolf år 1621.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 8,
                            CityId = 2,
                            ClueName = "Här finns Avenyn och Feskekörka.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 9,
                            CityId = 2,
                            ClueName = "Nöjesparken Liseberg ligger här.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 10,
                            CityId = 2,
                            ClueName = "Vi söker Sveriges näst största stad, vid Göta älvs mynning.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 11,
                            CityId = 3,
                            ClueName = "Vi reser till en stad i ett landskap som länge tillhörde Danmark.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 12,
                            CityId = 3,
                            ClueName = "Här finns både ett gammalt slott och en vriden skyskrapa.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 13,
                            CityId = 3,
                            ClueName = "Staden har en broförbindelse över Öresund till Danmark.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 14,
                            CityId = 3,
                            ClueName = "Här finns Turning Torso och Västra Hamnen.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 15,
                            CityId = 3,
                            ClueName = "Vi söker Skånes största stad.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 16,
                            CityId = 4,
                            ClueName = "Vi reser till en stad där vetenskap och kyrkohistoria möts.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 17,
                            CityId = 4,
                            ClueName = "Carl von Linné bodde och arbetade här.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 18,
                            CityId = 4,
                            ClueName = "Stadens universitet grundades år 1477.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 19,
                            CityId = 4,
                            ClueName = "Fyrisån rinner genom staden, som har en stor domkyrka.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 20,
                            CityId = 4,
                            ClueName = "Vi söker universitetsstaden norr om Stockholm med Gamla Uppsala i närheten.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 21,
                            CityId = 5,
                            ClueName = "Vi reser till en stad där industrihistoria möter en stor insjö.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 22,
                            CityId = 5,
                            ClueName = "Staden har en lång historia inom svensk elektroteknisk industri.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 23,
                            CityId = 5,
                            ClueName = "Här finns gravhögen Anundshög.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 24,
                            CityId = 5,
                            ClueName = "Staden ligger vid Mälaren och har gett namn åt Västeråsgurkan.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 25,
                            CityId = 5,
                            ClueName = "Vi söker staden som ofta kallas Gurkstaden.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 26,
                            CityId = 6,
                            ClueName = "Vår resa går till en stad i landskapet Närke.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 27,
                            CityId = 6,
                            ClueName = "Här finns ett välkänt vattentorn som också är ett besöksmål.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 28,
                            CityId = 6,
                            ClueName = "Svartån rinner genom stadens centrum.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 29,
                            CityId = 6,
                            ClueName = "Mitt i staden ligger ett slott på en ö, och vattentornet kallas Svampen.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 30,
                            CityId = 6,
                            ClueName = "Vi söker staden med Örebro slott.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 31,
                            CityId = 7,
                            ClueName = "Vi reser till en stad där flyghistoria och universitetsliv möts.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 32,
                            CityId = 7,
                            ClueName = "Staden ligger i Östergötland.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 33,
                            CityId = 7,
                            ClueName = "I närliggande Malmslätt finns Flygvapenmuseum.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 34,
                            CityId = 7,
                            ClueName = "Här finns friluftsmuseet Gamla Linköping och Stångån.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 35,
                            CityId = 7,
                            ClueName = "Vi söker staden som förknippas med Saab och flygplanet Gripen.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 36,
                            CityId = 8,
                            ClueName = "Vi reser till en stad där avståndet till Danmark är kort.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 37,
                            CityId = 8,
                            ClueName = "Här finns slottet Sofiero med sina trädgårdar.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 38,
                            CityId = 8,
                            ClueName = "Från staden går färjor till Helsingör.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 39,
                            CityId = 8,
                            ClueName = "Det medeltida tornet Kärnan blickar ut över Öresund.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 40,
                            CityId = 8,
                            ClueName = "Vi söker den skånska staden mitt emot Helsingör.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 41,
                            CityId = 9,
                            ClueName = "Vi reser till en stad i norra Sverige med ett rikt kulturliv.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 42,
                            CityId = 9,
                            ClueName = "Efter en stor brand 1888 planterades många träd här.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 43,
                            CityId = 9,
                            ClueName = "Staden var Europas kulturhuvudstad år 2014.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 44,
                            CityId = 9,
                            ClueName = "Umeälven rinner genom staden, som kallas Björkarnas stad.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 45,
                            CityId = 9,
                            ClueName = "Vi söker universitetsstaden Umeå.",
                            Point = 2m
                        },
                        new
                        {
                            ClueId = 46,
                            CityId = 10,
                            ClueName = "Vi reser till en skånsk stad med en lång akademisk historia.",
                            Point = 10m
                        },
                        new
                        {
                            ClueId = 47,
                            CityId = 10,
                            ClueName = "Universitetet här grundades år 1666.",
                            Point = 8m
                        },
                        new
                        {
                            ClueId = 48,
                            CityId = 10,
                            ClueName = "Staden har en medeltida domkyrka med ett astronomiskt ur.",
                            Point = 6m
                        },
                        new
                        {
                            ClueId = 49,
                            CityId = 10,
                            ClueName = "Här finns friluftsmuseet Kulturen och studenternas nationsliv.",
                            Point = 4m
                        },
                        new
                        {
                            ClueId = 50,
                            CityId = 10,
                            ClueName = "Vi söker universitetsstaden Lund, nära Malmö.",
                            Point = 2m
                        });
                });

            modelBuilder.Entity("Backend.Model.DailyChallange", b =>
                {
                    b.Property<int>("DailyChallangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DailyChallangeId"));

                    b.Property<DateTime>("ChallengDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("DailyChallangeId");

                    b.HasIndex("CityId");

                    b.ToTable("DailyChallanges");
                });

            modelBuilder.Entity("Backend.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyChallangeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GameId");

                    b.HasIndex("DailyChallangeId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Backend.Model.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            OptionId = 1,
                            IsCorrect = true,
                            OptionText = "Vasamuseet",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 2,
                            IsCorrect = false,
                            OptionText = "Sjöhistoriska museet",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 3,
                            IsCorrect = false,
                            OptionText = "Nordiska museet",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 4,
                            IsCorrect = false,
                            OptionText = "Tekniska museet",
                            QuestionId = 1
                        },
                        new
                        {
                            OptionId = 5,
                            IsCorrect = false,
                            OptionText = "Vättern",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 6,
                            IsCorrect = true,
                            OptionText = "Mälaren",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 7,
                            IsCorrect = false,
                            OptionText = "Vänern",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 8,
                            IsCorrect = false,
                            OptionText = "Siljan",
                            QuestionId = 2
                        },
                        new
                        {
                            OptionId = 9,
                            IsCorrect = false,
                            OptionText = "Gröna Lund",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 10,
                            IsCorrect = false,
                            OptionText = "Furuvik",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 11,
                            IsCorrect = true,
                            OptionText = "Liseberg",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 12,
                            IsCorrect = false,
                            OptionText = "Skara Sommarland",
                            QuestionId = 3
                        },
                        new
                        {
                            OptionId = 13,
                            IsCorrect = false,
                            OptionText = "Dalälven",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 14,
                            IsCorrect = false,
                            OptionText = "Umeälven",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 15,
                            IsCorrect = false,
                            OptionText = "Torne älv",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 16,
                            IsCorrect = true,
                            OptionText = "Göta älv",
                            QuestionId = 4
                        },
                        new
                        {
                            OptionId = 17,
                            IsCorrect = true,
                            OptionText = "Turning Torso",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 18,
                            IsCorrect = false,
                            OptionText = "Kaknästornet",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 19,
                            IsCorrect = false,
                            OptionText = "Karlatornet",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 20,
                            IsCorrect = false,
                            OptionText = "Kista Science Tower",
                            QuestionId = 5
                        },
                        new
                        {
                            OptionId = 21,
                            IsCorrect = false,
                            OptionText = "Århus",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 22,
                            IsCorrect = true,
                            OptionText = "Köpenhamn",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 23,
                            IsCorrect = false,
                            OptionText = "Odense",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 24,
                            IsCorrect = false,
                            OptionText = "Ålborg",
                            QuestionId = 6
                        },
                        new
                        {
                            OptionId = 25,
                            IsCorrect = false,
                            OptionText = "Svartån",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 26,
                            IsCorrect = false,
                            OptionText = "Stångån",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 27,
                            IsCorrect = true,
                            OptionText = "Fyrisån",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 28,
                            IsCorrect = false,
                            OptionText = "Motala ström",
                            QuestionId = 7
                        },
                        new
                        {
                            OptionId = 29,
                            IsCorrect = false,
                            OptionText = "Alfred Nobel",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 30,
                            IsCorrect = false,
                            OptionText = "Anders Celsius",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 31,
                            IsCorrect = false,
                            OptionText = "Gustaf Dalén",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 32,
                            IsCorrect = true,
                            OptionText = "Carl von Linné",
                            QuestionId = 8
                        },
                        new
                        {
                            OptionId = 33,
                            IsCorrect = true,
                            OptionText = "Mälaren",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 34,
                            IsCorrect = false,
                            OptionText = "Vänern",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 35,
                            IsCorrect = false,
                            OptionText = "Vättern",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 36,
                            IsCorrect = false,
                            OptionText = "Hjälmaren",
                            QuestionId = 9
                        },
                        new
                        {
                            OptionId = 37,
                            IsCorrect = false,
                            OptionText = "Hågahögen",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 38,
                            IsCorrect = true,
                            OptionText = "Anundshög",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 39,
                            IsCorrect = false,
                            OptionText = "Inglingehög",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 40,
                            IsCorrect = false,
                            OptionText = "Kung Björns hög",
                            QuestionId = 10
                        },
                        new
                        {
                            OptionId = 41,
                            IsCorrect = false,
                            OptionText = "Kronan",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 42,
                            IsCorrect = false,
                            OptionText = "Koppen",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 43,
                            IsCorrect = true,
                            OptionText = "Svampen",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 44,
                            IsCorrect = false,
                            OptionText = "Fyren",
                            QuestionId = 11
                        },
                        new
                        {
                            OptionId = 45,
                            IsCorrect = false,
                            OptionText = "Dalarna",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 46,
                            IsCorrect = false,
                            OptionText = "Bohuslän",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 47,
                            IsCorrect = false,
                            OptionText = "Blekinge",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 48,
                            IsCorrect = true,
                            OptionText = "Närke",
                            QuestionId = 12
                        },
                        new
                        {
                            OptionId = 49,
                            IsCorrect = true,
                            OptionText = "Stångån",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 50,
                            IsCorrect = false,
                            OptionText = "Fyrisån",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 51,
                            IsCorrect = false,
                            OptionText = "Rönne å",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 52,
                            IsCorrect = false,
                            OptionText = "Nissan",
                            QuestionId = 13
                        },
                        new
                        {
                            OptionId = 53,
                            IsCorrect = false,
                            OptionText = "Vasamuseet",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 54,
                            IsCorrect = true,
                            OptionText = "Flygvapenmuseum",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 55,
                            IsCorrect = false,
                            OptionText = "Järnvägsmuseet",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 56,
                            IsCorrect = false,
                            OptionText = "Marinmuseum",
                            QuestionId = 14
                        },
                        new
                        {
                            OptionId = 57,
                            IsCorrect = false,
                            OptionText = "Kaknästornet",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 58,
                            IsCorrect = false,
                            OptionText = "Svampen",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 59,
                            IsCorrect = true,
                            OptionText = "Kärnan",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 60,
                            IsCorrect = false,
                            OptionText = "Jungfrutornet",
                            QuestionId = 15
                        },
                        new
                        {
                            OptionId = 61,
                            IsCorrect = false,
                            OptionText = "Köpenhamn",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 62,
                            IsCorrect = false,
                            OptionText = "Århus",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 63,
                            IsCorrect = false,
                            OptionText = "Odense",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 64,
                            IsCorrect = true,
                            OptionText = "Helsingör",
                            QuestionId = 16
                        },
                        new
                        {
                            OptionId = 65,
                            IsCorrect = true,
                            OptionText = "Björkarnas stad",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 66,
                            IsCorrect = false,
                            OptionText = "Gurkstaden",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 67,
                            IsCorrect = false,
                            OptionText = "Solstaden",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 68,
                            IsCorrect = false,
                            OptionText = "Lilla London",
                            QuestionId = 17
                        },
                        new
                        {
                            OptionId = 69,
                            IsCorrect = false,
                            OptionText = "Luleälven",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 70,
                            IsCorrect = true,
                            OptionText = "Umeälven",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 71,
                            IsCorrect = false,
                            OptionText = "Dalälven",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 72,
                            IsCorrect = false,
                            OptionText = "Göta älv",
                            QuestionId = 18
                        },
                        new
                        {
                            OptionId = 73,
                            IsCorrect = false,
                            OptionText = "1477",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 74,
                            IsCorrect = false,
                            OptionText = "1621",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 75,
                            IsCorrect = true,
                            OptionText = "1666",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 76,
                            IsCorrect = false,
                            OptionText = "1810",
                            QuestionId = 19
                        },
                        new
                        {
                            OptionId = 77,
                            IsCorrect = false,
                            OptionText = "Skansen",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 78,
                            IsCorrect = false,
                            OptionText = "Gamla Linköping",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 79,
                            IsCorrect = false,
                            OptionText = "Wadköping",
                            QuestionId = 20
                        },
                        new
                        {
                            OptionId = 80,
                            IsCorrect = true,
                            OptionText = "Kulturen",
                            QuestionId = 20
                        });
                });

            modelBuilder.Entity("Backend.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.HasIndex("CityId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CityId = 1,
                            QuestionText = "Vad heter museet som visar krigsskeppet Vasa?"
                        },
                        new
                        {
                            QuestionId = 2,
                            CityId = 1,
                            QuestionText = "Vilken sjö ligger väster om Stockholm?"
                        },
                        new
                        {
                            QuestionId = 3,
                            CityId = 2,
                            QuestionText = "Vilken nöjespark ligger i Göteborg?"
                        },
                        new
                        {
                            QuestionId = 4,
                            CityId = 2,
                            QuestionText = "Vilken älv rinner genom Göteborg?"
                        },
                        new
                        {
                            QuestionId = 5,
                            CityId = 3,
                            QuestionText = "Vad heter den vridna skyskrapan i Malmö?"
                        },
                        new
                        {
                            QuestionId = 6,
                            CityId = 3,
                            QuestionText = "Vilken dansk stad förbinder Öresundsbron Malmö med?"
                        },
                        new
                        {
                            QuestionId = 7,
                            CityId = 4,
                            QuestionText = "Vilken å rinner genom Uppsala?"
                        },
                        new
                        {
                            QuestionId = 8,
                            CityId = 4,
                            QuestionText = "Vilken botaniker förknippas med Uppsala?"
                        },
                        new
                        {
                            QuestionId = 9,
                            CityId = 5,
                            QuestionText = "Vid vilken sjö ligger Västerås?"
                        },
                        new
                        {
                            QuestionId = 10,
                            CityId = 5,
                            QuestionText = "Vad heter den stora gravhögen i Västerås?"
                        },
                        new
                        {
                            QuestionId = 11,
                            CityId = 6,
                            QuestionText = "Vad kallas det välkända vattentornet i Örebro?"
                        },
                        new
                        {
                            QuestionId = 12,
                            CityId = 6,
                            QuestionText = "I vilket landskap ligger Örebro?"
                        },
                        new
                        {
                            QuestionId = 13,
                            CityId = 7,
                            QuestionText = "Vilken å rinner genom Linköping?"
                        },
                        new
                        {
                            QuestionId = 14,
                            CityId = 7,
                            QuestionText = "Vilket museum ligger i Malmslätt nära Linköping?"
                        },
                        new
                        {
                            QuestionId = 15,
                            CityId = 8,
                            QuestionText = "Vad heter det medeltida tornet i Helsingborg?"
                        },
                        new
                        {
                            QuestionId = 16,
                            CityId = 8,
                            QuestionText = "Till vilken dansk stad går färjorna från Helsingborg?"
                        },
                        new
                        {
                            QuestionId = 17,
                            CityId = 9,
                            QuestionText = "Vilket smeknamn har Umeå?"
                        },
                        new
                        {
                            QuestionId = 18,
                            CityId = 9,
                            QuestionText = "Vilken älv rinner genom Umeå?"
                        },
                        new
                        {
                            QuestionId = 19,
                            CityId = 10,
                            QuestionText = "Vilket år grundades Lunds universitet?"
                        },
                        new
                        {
                            QuestionId = 20,
                            CityId = 10,
                            QuestionText = "Vad heter friluftsmuseet i Lund?"
                        });
                });

            modelBuilder.Entity("Backend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Model.Clue", b =>
                {
                    b.HasOne("Backend.Model.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Backend.Model.DailyChallange", b =>
                {
                    b.HasOne("Backend.Model.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Backend.Model.Game", b =>
                {
                    b.HasOne("Backend.Model.DailyChallange", "DailyChallange")
                        .WithMany()
                        .HasForeignKey("DailyChallangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyChallange");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Model.Option", b =>
                {
                    b.HasOne("Backend.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Model.Question", b =>
                {
                    b.HasOne("Backend.Model.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Backend.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Backend.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Backend.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
